# Generated by Django 2.2.2 on 2019-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Description of the eBook')),
                ('slug', models.SlugField(unique=True, verbose_name=models.CharField(max_length=100))),
                ('URL', models.URLField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
