# Generated by Django 2.2.2 on 2019-06-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book'),
    ]
    operations = []
