# Generated by Django 2.2.2 on 2019-06-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190625_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='URL',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
