# Generated by Django 2.2.2 on 2019-06-25 18:04

from django.db import migrations
from django.conf import settings
import csv
import os


def intial_data_from_csv(apps, schema_editor):
    Book = apps.get_model('core', 'Book')
    filename = os.path.join(settings.BASE_DIR, 'sample_books.csv')

    with open(filename) as file:
        reader = csv.DictReader(file)
        for row in reader:
            book = Book(title=row['title'],
                        author=row['author'],
                        url=row['url'],
                        description=row['description'])
            book.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190625_1401'),
    ]

    operations = [migrations.RunPython(intial_data_from_csv, do_nothing)]
