# Generated by Django 2.2.2 on 2019-06-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190625_1404'),
    ]

    operations = [
    ]
