# Generated by Django 2.2.2 on 2019-06-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190627_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['date_added']},
        ),
    ]
