# Generated by Django 2.2.2 on 2019-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190628_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, verbose_name=models.CharField(max_length=100)),
        ),
    ]
