# Generated by Django 2.2.2 on 2019-06-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='times_favorited',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
